# Use phusion/baseimage as base image.
FROM phusion/baseimage:latest

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# custom build instructions here...
# Java: OpenJDK8
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update
RUN apt-get -y install openjdk-8-jdk monit
ADD hystrix-0.0.1-SNAPSHOT.jar /hystrix-0.0.1-SNAPSHOT.jar
RUN mkdir /etc/service/ega_v3_hystrix
ADD hystrixd.sh /etc/service/ega_v3_hystrix/run
RUN chmod +x /etc/service/ega_v3_hystrix/run
ADD hystrixd.sh /etc/hystrixd.sh
RUN chmod +x /etc/hystrixd.sh
ADD monitrc /etc/monitrc
RUN chmod 700 /etc/monitrc

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Startup
CMD monit -d 10 -Ic /etc/monitrc

# Port
EXPOSE 8088 8103
